meta_product_name: “SimpleRent

meta_title: “SimpleRent – The one-stop-shop to rent and rent out anything"

meta_description: "This platform is the place to rent, lease, host, store, rent out, all your items, units, boats, cars, tents, kayaks, bicycles, create your own shop"

meta_image: "logo.png”
